FROM python:3.12-slim

WORKDIR /app

# Install uv (modern dependency manager)
RUN pip install uv

# Copy only what we need to install dependencies
COPY uv.lock pyproject.toml ./
RUN uv sync --no-install-project

# Copy and install the built wheel (app is inside)
# COPY dist/address_validator-*.whl .
# RUN pip install --no-deps address_validator-*.whl

# Expose port (optional, for docs and some platforms)
# EXPOSE 8000

# CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
CMD ["python", "-m", "pip", "list"]
